## Imports

In [1]:
# to convert into dataframes
import pandas as pd

# extract url response/info
from urllib.request import urlopen

# to work with html content
from bs4 import BeautifulSoup

## Fetch T20I - Batting Ratings & Rankings - with Date (ex: 1st Jan 2021)

- **Note: Here date format = (YYYY/MM/DD)** 
- 1st Jan 2021 = 2021/01/01
- 10th Jan 2021 = 2021/01/10

In [2]:
['2021/01/' + str(i) for i in range(1, 32)]

['2021/01/1',
 '2021/01/2',
 '2021/01/3',
 '2021/01/4',
 '2021/01/5',
 '2021/01/6',
 '2021/01/7',
 '2021/01/8',
 '2021/01/9',
 '2021/01/10',
 '2021/01/11',
 '2021/01/12',
 '2021/01/13',
 '2021/01/14',
 '2021/01/15',
 '2021/01/16',
 '2021/01/17',
 '2021/01/18',
 '2021/01/19',
 '2021/01/20',
 '2021/01/21',
 '2021/01/22',
 '2021/01/23',
 '2021/01/24',
 '2021/01/25',
 '2021/01/26',
 '2021/01/27',
 '2021/01/28',
 '2021/01/29',
 '2021/01/30',
 '2021/01/31']

In [3]:
date = '2021/01/01'
url = "https://www.relianceiccrankings.com/ranking/t20/batting/" + date + "/"
text = urlopen(url)
soup = BeautifulSoup(text, "lxml")
table = soup.findAll('table')

cols = len(table[0].findAll('tr')[0].findAll('th'))
rows = len(table[0].findAll('tr'))

all_players = []

for k in range(1, rows):
    
    # iterate through all rows
    row_data = []
    for col in range(1, cols + 1):
        text = table[0].findAll('tr')[k].findAll('td')[col].get_text()
        text = text.replace('\n','')
        row_data.append(text)
        
    all_players.append(row_data)
        
    # populate column names
    tr_list_columns = table[0].findAll('tr')[0].findAll('th')
    cols_count = len(tr_list_columns)
    
    column_names_ls = []
    for i in range(cols_count):
        column_name = tr_list_columns[i].get_text()
        column_names_ls.append(column_name)
        
    # convert to dataframe
df = pd.DataFrame(all_players, columns = column_names_ls)

In [4]:
df

,Rating,Name,,Career Best T20 Rating,Career Best T20 Ranking
0,841,Dawid Malan,,"915 v South Africa, 01/12/2020","1 v Australia,on 04/09/2020"
1,819,Babar Azam,,"896 v England, 05/05/2019","1 v New Zealand,on 28/01/2018"
2,795,Aaron Finch,,"900 v Zimbabwe, 03/07/2018","1 v South Africa,on 14/03/2014"
3,774,Devon Conway,,"784 v Bangladesh, 28/03/2021","4 v Bangladesh,on 28/03/2021"
4,717,Virat Kohli,,"897 v England, 07/09/2014","1 v England,on 07/09/2014"
...,...,...,...,...,...
95,357,Gyanendra Malla,,"357 v Netherlands, 24/04/2021","85 v Netherlands,on 03/07/2015"
96,356,Nitish Kumar,,"360 v Oman, 25/10/2019","80 v Oman,on 25/10/2019"
97,354,Manish Pandey,,"529 v Ireland, 29/06/2018","33 v Bangladesh,on 18/03/2018"
98,349,Ramesh Satheesan,,"349 v Bulgaria, 27/06/2021","95 v Bulgaria,on 27/06/2021"
99,344,Samiullah Samiullah Shenwari,,"470 v Bangladesh, 07/06/2018","46 v Ireland,on 08/03/2017"

In [20]:
def fetch_ratings_df(over_format, player_role, date):
    url = "https://www.relianceiccrankings.com/ranking/" + over_format + '/' + player_role + '/' + date + '/'
    url = "https://www.relianceiccrankings.com/datespecific/" + over_format + '/' + player_role + '/' + date + '/'
    print(url)
    text = urlopen(url)
    soup = BeautifulSoup(text, "lxml")
    table = soup.findAll('table')

    cols = len(table[0].findAll('tr')[0].findAll('th'))
    rows = len(table[0].findAll('tr'))

    all_players = []

    for k in range(1, rows):

        # iterate through all rows
        row_data = []
        for col in range(1, cols + 1):
            text = table[0].findAll('tr')[k].findAll('td')[col].get_text()
            text = text.replace('\n','')
            row_data.append(text)

        all_players.append(row_data)

        # populate column names
        tr_list_columns = table[0].findAll('tr')[0].findAll('th')
        cols_count = len(tr_list_columns)

        column_names_ls = []
        for i in range(cols_count):
            column_name = tr_list_columns[i].get_text()
            column_names_ls.append(column_name)

        # convert to dataframe
    df = pd.DataFrame(all_players, columns = column_names_ls)
    
    return df

## Fetch data for any Format, Role & Date:
- Over_format = test, odi, t20
- Player_role = batting, bowling, all-rounder
- Date = 'YYYY/MM/DD'

In [25]:
over_format = 'odi'
player_role = 'all-rounder'
date = '2020/10/01'

df = fetch_ratings_df(over_format, player_role, date)

https://www.relianceiccrankings.com/datespecific/odi/all-rounder/2020/10/01/

In [26]:
df

,Rating,Name,,Career Best ODI Rating,Career Best ODI Ranking
0,301,Mohammad Mohammad Nabi,,"349 v Ireland, 15/03/2017","2 v Zimbabwe,on 16/02/2017"
1,281,Chris Woakes,,"313 v New Zealand, 10/03/2018","2 v Australia,on 16/09/2020"
2,278,Imad Wasim,,"300 v Bangladesh, 05/07/2019","3 v Zimbabwe,on 30/10/2020"
3,276,Ben Stokes,,"319 v New Zealand, 14/07/2019","2 v Australia,on 11/07/2019"
4,265,Colin de Grandhomme,,"266 v India, 11/02/2020","4 v India,on 11/02/2020"
5,253,Rashid Khan,,"359 v Pakistan, 21/09/2018","1 v India,on 25/09/2018"
6,251,Mitchell Santner,,"317 v England, 10/03/2018","4 v England,on 10/03/2018"
7,246,Ravindra Jadeja,,"378 v England, 23/06/2013","2 v Zimbabwe,on 01/08/2013"
8,232,Sikandar Raza,,"275 v Ireland, 16/03/2018","8 v Sri Lanka,on 17/01/2018"
9,229,Sean Williams,,"241 v Sri Lanka, 30/06/2017","10 v Bangladesh,on 03/03/2020"